// Package env provides small, dependency-free helpers around os.Getenv for
// reading and requiring environment variables, with optional typed defaults.
//
// Get returns the value of an environment variable, falling back to the
// first supplied default if the variable is unset. Require returns the
// value of an environment variable and a *NotSetError if it is unset.
//
// Typed variants (GetInt, RequireInt, GetBool, RequireBool, ...) are
// generated by go generate; see internal/gen. They return an error rather
// than panicking, so a malformed value (e.g. PORT="abc") is reported the
// same way a missing one is.
package env

import "os"

//go:generate go run ./internal/gen

// Get returns the value of the environment variable named by key.
//
// If the variable is set, its value is returned. Otherwise, the first
// value in defaults is returned. If the variable is unset and no defaults
// are provided, an empty string is returned.
func Get(key string, defaults ...string) string {
	if v, ok := os.LookupEnv(key); ok {
		return v
	}
	if len(defaults) > 0 {
		return defaults[0]
	}
	return ""
}

// Require returns the value of the environment variable named by key.
//
// It returns a *NotSetError if the variable is not set. Use this for
// configuration that the program cannot sensibly run without.
func Require(key string) (string, error) {
	v, ok := os.LookupEnv(key)
	if !ok {
		return "", &NotSetError{Key: key}
	}
	return v, nil
}
