// Code generated by internal/gen; DO NOT EDIT.

package env

import (
	"os"
	"strconv"
	"time"
)

// GetInt returns the int value of the environment variable
// named by key.
//
// If the variable is set, it is parsed as int. If the variable is
// unset, the first value in defaults is returned, or the zero value of
// int if no defaults are provided. It returns a *ParseError if the
// variable is set but cannot be parsed as int.
func GetInt(key string, defaults ...int) (int, error) {
	raw, ok := os.LookupEnv(key)
	if !ok {
		if len(defaults) > 0 {
			return defaults[0], nil
		}
		var zero int
		return zero, nil
	}
	val, err := strconv.Atoi(raw)
	if err != nil {
		var zero int
		return zero, &ParseError{Key: key, Value: raw, Type: "int", Err: err}
	}
	return val, nil
}

// RequireInt returns the int value of the environment
// variable named by key.
//
// It returns a *NotSetError if the variable is not set, or a *ParseError if
// it is set but cannot be parsed as int.
func RequireInt(key string) (int, error) {
	raw, ok := os.LookupEnv(key)
	if !ok {
		var zero int
		return zero, &NotSetError{Key: key}
	}
	val, err := strconv.Atoi(raw)
	if err != nil {
		var zero int
		return zero, &ParseError{Key: key, Value: raw, Type: "int", Err: err}
	}
	return val, nil
}

// GetInt64 returns the int64 value of the environment variable
// named by key.
//
// If the variable is set, it is parsed as int64. If the variable is
// unset, the first value in defaults is returned, or the zero value of
// int64 if no defaults are provided. It returns a *ParseError if the
// variable is set but cannot be parsed as int64.
func GetInt64(key string, defaults ...int64) (int64, error) {
	raw, ok := os.LookupEnv(key)
	if !ok {
		if len(defaults) > 0 {
			return defaults[0], nil
		}
		var zero int64
		return zero, nil
	}
	val, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		var zero int64
		return zero, &ParseError{Key: key, Value: raw, Type: "int64", Err: err}
	}
	return val, nil
}

// RequireInt64 returns the int64 value of the environment
// variable named by key.
//
// It returns a *NotSetError if the variable is not set, or a *ParseError if
// it is set but cannot be parsed as int64.
func RequireInt64(key string) (int64, error) {
	raw, ok := os.LookupEnv(key)
	if !ok {
		var zero int64
		return zero, &NotSetError{Key: key}
	}
	val, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		var zero int64
		return zero, &ParseError{Key: key, Value: raw, Type: "int64", Err: err}
	}
	return val, nil
}

// GetFloat64 returns the float64 value of the environment variable
// named by key.
//
// If the variable is set, it is parsed as float64. If the variable is
// unset, the first value in defaults is returned, or the zero value of
// float64 if no defaults are provided. It returns a *ParseError if the
// variable is set but cannot be parsed as float64.
func GetFloat64(key string, defaults ...float64) (float64, error) {
	raw, ok := os.LookupEnv(key)
	if !ok {
		if len(defaults) > 0 {
			return defaults[0], nil
		}
		var zero float64
		return zero, nil
	}
	val, err := strconv.ParseFloat(raw, 64)
	if err != nil {
		var zero float64
		return zero, &ParseError{Key: key, Value: raw, Type: "float64", Err: err}
	}
	return val, nil
}

// RequireFloat64 returns the float64 value of the environment
// variable named by key.
//
// It returns a *NotSetError if the variable is not set, or a *ParseError if
// it is set but cannot be parsed as float64.
func RequireFloat64(key string) (float64, error) {
	raw, ok := os.LookupEnv(key)
	if !ok {
		var zero float64
		return zero, &NotSetError{Key: key}
	}
	val, err := strconv.ParseFloat(raw, 64)
	if err != nil {
		var zero float64
		return zero, &ParseError{Key: key, Value: raw, Type: "float64", Err: err}
	}
	return val, nil
}

// GetBool returns the bool value of the environment variable
// named by key.
//
// If the variable is set, it is parsed as bool. If the variable is
// unset, the first value in defaults is returned, or the zero value of
// bool if no defaults are provided. It returns a *ParseError if the
// variable is set but cannot be parsed as bool.
func GetBool(key string, defaults ...bool) (bool, error) {
	raw, ok := os.LookupEnv(key)
	if !ok {
		if len(defaults) > 0 {
			return defaults[0], nil
		}
		var zero bool
		return zero, nil
	}
	val, err := strconv.ParseBool(raw)
	if err != nil {
		var zero bool
		return zero, &ParseError{Key: key, Value: raw, Type: "bool", Err: err}
	}
	return val, nil
}

// RequireBool returns the bool value of the environment
// variable named by key.
//
// It returns a *NotSetError if the variable is not set, or a *ParseError if
// it is set but cannot be parsed as bool.
func RequireBool(key string) (bool, error) {
	raw, ok := os.LookupEnv(key)
	if !ok {
		var zero bool
		return zero, &NotSetError{Key: key}
	}
	val, err := strconv.ParseBool(raw)
	if err != nil {
		var zero bool
		return zero, &ParseError{Key: key, Value: raw, Type: "bool", Err: err}
	}
	return val, nil
}

// GetDuration returns the time.Duration value of the environment variable
// named by key.
//
// If the variable is set, it is parsed as time.Duration. If the variable is
// unset, the first value in defaults is returned, or the zero value of
// time.Duration if no defaults are provided. It returns a *ParseError if the
// variable is set but cannot be parsed as time.Duration.
func GetDuration(key string, defaults ...time.Duration) (time.Duration, error) {
	raw, ok := os.LookupEnv(key)
	if !ok {
		if len(defaults) > 0 {
			return defaults[0], nil
		}
		var zero time.Duration
		return zero, nil
	}
	val, err := time.ParseDuration(raw)
	if err != nil {
		var zero time.Duration
		return zero, &ParseError{Key: key, Value: raw, Type: "time.Duration", Err: err}
	}
	return val, nil
}

// RequireDuration returns the time.Duration value of the environment
// variable named by key.
//
// It returns a *NotSetError if the variable is not set, or a *ParseError if
// it is set but cannot be parsed as time.Duration.
func RequireDuration(key string) (time.Duration, error) {
	raw, ok := os.LookupEnv(key)
	if !ok {
		var zero time.Duration
		return zero, &NotSetError{Key: key}
	}
	val, err := time.ParseDuration(raw)
	if err != nil {
		var zero time.Duration
		return zero, &ParseError{Key: key, Value: raw, Type: "time.Duration", Err: err}
	}
	return val, nil
}
